### PR TITLE
DynamicalSystems => PredefinedDynamicalSystems for the docs

### PR DESCRIPTION
**Pull request by MartinuzziFrancesco**

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by MartinuzziFrancesco** [comment]
@ChrisRackauckas how can I access the buildkite build to see what's failing?

**Comment by ChrisRackauckas** [comment]
```
<html>
<body>
<!--StartFragment-->

│ using PredefinedDynamicalSystems
--
  | │ train_len = 3000
  | │ predict_len = 2000
  | │
  | │ ds = PredefinedDynamicalSystems.henon()
  | │ data, time = trajectory(ds, 7000)
  | │ data = Matrix(traj)'
  | │ data = (data .-0.5) .* 2
  | │ shift = 200
  | │
  | │ training_input = data[:, shift:shift+train_len-1]
  | │ training_target = data[:, shift+1:shift+train_len]
  | │ testing_input = data[:,shift+train_len:shift+train_len+predict_len-1]
  | │ testing_target = data[:,shift+train_len+1:shift+train_len+predict_len]
  | │ ```
  | │   value =
  | │    UndefVarError: traj not defined
  | │
  | │    Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
  | │    in the stack trace, evaluate `TruncatedStacktraces.VERBOSE[] = true` and re-run the code.

<!--EndFragment-->
</body>
</html>
```

**Comment by ChrisRackauckas** [comment]
you should be able to just read it, it's a public run.

**Comment by MartinuzziFrancesco** [comment]
weird, I get a `page not found` link

**Pull request merged**
