### PR TITLE
Docs work

### PR DESCRIPTION
**Pull request by MartinuzziFrancesco**
Adding `@example` and fixing minor things

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Skip the GPU one for now. That'll need an issue and a change to the buildkite

**Comment by MartinuzziFrancesco** [comment]
ok thanks I didn't know how to proceed on that one

**Comment by ChrisRackauckas** [comment]
Is there a good tutorial to elevate to a `getting_started`?

**Comment by ChrisRackauckas** [comment]
Also, please split tutorials and examples

**Comment by MartinuzziFrancesco** [comment]
I think the Lorenz example should work well as a `getting_started`. As a rule of thumb what would be a tutorial and what an example? at the moment the structure uses the examples as tutorials

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/ModelingToolkit.jl/pull/1993

Tutorials should be around specific topics of the package, demonstrating something "most" people should know. Examples are more centered around showing a complex example, maybe with less text. If you have two tutorials around the same topic, one should be kept as tutorial and the other should be demoted to example.

Lorenz is a good getting started.

**Comment by MartinuzziFrancesco** [comment]
Ok I see, that'll take some reorganization. I think that we could merge this pr when everything is up to speed and I'll open a new one for the restructure of the docs specifically.

I can't figure out where [this](https://github.com/SciML/ReservoirComputing.jl/actions/runs/3669953922/jobs/6204152002#step:5:29) is coming from

**Pull request merged**
